- hosts: all
  gather_facts: false
  tasks:

  # See https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_key_module.html#examples
  - name: Add Dropbox apt repository signing key
    become: yes
    become_user: root
    apt_key:
      keyserver: keyserver.ubuntu.com
      id: FC918B335044912E
      state: present

  - name: Add Dropbox repo
    become: yes
    become_user: root
    deb822_repository:
      name: dropbox
      types: deb
      uris: http://linux.dropbox.com/debian
      suites: bookworm
      components:
        - main
      architectures: amd64
      state: present
      enabled: true

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install python3-gpg
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: python3-gpg

  - name: Install Dropbox
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: dropbox
