# https://support.mozilla.org/en-US/kb/install-firefox-linux#w_install-firefox-deb-package-for-debian-based-distributions

- hosts: all
  gather_facts: false
  tasks:

  - name: Add Mozilla repo
    become: yes
    become_user: root
    deb822_repository:
      name: firefox
      types: deb
      uris: https://packages.mozilla.org/apt
      suites: mozilla
      components:
        - main
      architectures: amd64
      signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg
      state: present
      enabled: true

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Firefox
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: firefox
