- hosts: all
  gather_facts: false
  tasks:

  - name: Add Firefox apt repository signing key
    become: yes
    become_user: root
    apt_key:
      url: https://packages.mozilla.org/apt/repo-signing-key.gpg
      state: present

  - name: Add Firefox apt repo
    become: yes
    become_user: root
    apt_repository:
      repo: deb https://packages.mozilla.org/apt mozilla main
      state: present

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Firefox
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: firefox
