- hosts: all
  gather_facts: false
  tasks:

  - name: Add Google repo
    become: yes
    become_user: root
    deb822_repository:
      name: google
      types: deb
      uris: http://dl.google.com/linux/chrome/deb/
      suites: stable
      components:
        - main
      architectures: amd64
      signed_by: https://dl.google.com/linux/linux_signing_key.pub
      state: present
      enabled: true

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Google Chrome
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: google-chrome-stable
