- hosts: all
  gather_facts: false
  tasks:

  - name: Create cthulhu.org registry key
    become: yes
    become_user: root
    openssl_privatekey:
      owner: root
      group: ssl-cert
      path: /etc/ssl/private/cthulhu.org.key

  - name: Look for cthulhu.org registry certificate
    become: yes
    become_user: root
    stat:
      path: /etc/ssl/certs/cthulhu.org.crt
    register: gotosocial_registry_certificate

  - name: Create cthulhu.org registry certificate Signing Request
    when: gotosocial_registry_certificate.stat.exists == False
    become: yes
    become_user: root
    openssl_csr:
      privatekey_path: /etc/ssl/private/cthulhu.org.key
      path: /tmp/cthulhu.org.csr
      common_name: cthulhu.org

  - name: Create cthulhu.org registry certificate
    when: gotosocial_registry_certificate.stat.exists == False
    become: yes
    become_user: root
    openssl_certificate:
      provider: ownca
      ownca_path: /etc/ssl/certs/localhost_CA.pem
      ownca_privatekey_path: /etc/ssl/private/localhost_CA.key
      privatekey_path: /etc/ssl/private/cthulhu.org.key
      csr_path: /tmp/cthulhu.org.csr
      path: /etc/ssl/certs/cthulhu.org.crt
