- hosts: all
  gather_facts: false
  tasks:

  - name: Create gotosocial.localhost registry key
    become: yes
    become_user: root
    openssl_privatekey:
      owner: root
      group: ssl-cert
      path: /etc/ssl/private/gotosocial.localhost.key

  - name: Look for gotosocial.localhost registry certificate
    become: yes
    become_user: root
    stat:
      path: /etc/ssl/certs/gotosocial.localhost.crt
    register: gotosocial_registry_certificate

  - name: Create gotosocial.localhost registry certificate Signing Request
    when: gotosocial_registry_certificate.stat.exists == False
    become: yes
    become_user: root
    openssl_csr:
      privatekey_path: /etc/ssl/private/gotosocial.localhost.key
      path: /tmp/gotosocial.localhost.csr
      common_name: gotosocial.localhost

  - name: Create gotosocial.localhost registry certificate
    when: gotosocial_registry_certificate.stat.exists == False
    become: yes
    become_user: root
    openssl_certificate:
      provider: ownca
      ownca_path: /etc/ssl/certs/localhost_CA.pem
      ownca_privatekey_path: /etc/ssl/private/localhost_CA.key
      privatekey_path: /etc/ssl/private/gotosocial.localhost.key
      csr_path: /tmp/gotosocial.localhost.csr
      path: /etc/ssl/certs/gotosocial.localhost.crt
