# This needs updating. See https://help.mega.io/installs-apps/desktop/linux
- hosts: all
  tasks:

  - name: Download MEGA DEB package
    get_url:
      url="https://mega.nz/linux/repo/Debian_testing/amd64/megasync_5.6.0-1.1_amd64.deb"
      dest="/tmp/megasync_5.6.0-1.1_amd64.deb"

  - name: Install MEGA DEB package
    become: true
    become_user: root
    apt: deb=/tmp/megasync_5.6.0-1.1_amd64.deb

  - name: Download MEGA Nautilus integration DEB package
    get_url:
      url="https://mega.nz/linux/repo/Debian_testing/amd64/nautilus-megasync_5.3.0-2.1_amd64.deb"
      dest="/tmp/nautilus-megasync_5.3.0-2.1_amd64.deb"

  - name: Install MEGA DEB package
    become: true
    become_user: root
    apt: deb=/tmp/nautilus-megasync_5.3.0-2.1_amd64.deb
