- hosts: all
  tasks:

  - name: Download NordVPN DEB package
    get_url:
      url=https://repo.nordvpn.com/deb/nordvpn/debian/pool/main/nordvpn-release_1.0.0_all.deb
      dest=/tmp/nordvpn-release_1.0.0_all.deb

  - name: Install NordVPN DEB package (configures repo)
    become: true
    become_user: root
    apt: deb=/tmp/nordvpn-release_1.0.0_all.deb

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install NordVPN
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: nordvpn

  - name: Add this user to group nordvpn
    become: yes
    become_user: root
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: nordvpn
      append: yes

  - debug:
      msg: "You have to logout and back in, otherwise group changes will not take effect"
