# See https://downloads.nordcdn.com/apps/linux/install.sh
- hosts: all
  gather_facts: false
  tasks:

  - name: Install apt-transport-https
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: apt-transport-https

  - name: Add NordVPN repo
    become: yes
    become_user: root
    deb822_repository:
      name: nordvpn
      types: deb
      uris: https://repo.nordvpn.com/deb/nordvpn/debian
      suites: stable
      components:
        - main
      architectures: amd64
      signed_by: https://repo.nordvpn.com/gpg/nordvpn_public.asc
      state: present
      enabled: true

  - name: Update apt cache
    become: yes
    become_user: root
    apt:
      update_cache: yes

  - name: Install NordVPN
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: nordvpn

  - name: Add this user to group nordvpn
    become: yes
    become_user: root
    user:
      name: "{{ lookup('env', 'USER') }}"
      groups: nordvpn
      append: yes

  - debug:
      msg: "You have to logout and back in, otherwise group changes will not take effect"
