# From https://signal.org/download

- hosts: all
  gather_facts: false
  tasks:

  - name: Add Signal repo
    become: yes
    become_user: root
    deb822_repository:
      name: signal
      types: deb
      uris: https://updates.signal.org/desktop/apt
      suites: xenial
      components:
        - main
      architectures: amd64
      signed_by: https://updates.signal.org/desktop/apt/keys.asc
      state: present
      enabled: true

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install signal
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: signal-desktop
