# https://packagecloud.io/slacktechnologies/slack/install#manual-deb
#
# The examples have references to Ubuntu repositories, but looks like
# there are only Debian ones. Jessie is the latest

- hosts: all
  gather_facts: false
  tasks:

  - name: Add Slack repo
    become: yes
    become_user: root
    deb822_repository:
      name: slack
      types: deb
      uris: https://packagecloud.io/slacktechnologies/slack/debian/
      suites: jessie
      components:
        - main
      architectures: amd64
      signed_by: https://packagecloud.io/slacktechnologies/slack/gpgkey
      state: present
      enabled: true

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install slack-desktop
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: slack-desktop
