- hosts: all
  gather_facts: false
  tasks:

  - name: Add Spotify apt repository signing key
    become: yes
    become_user: root
    apt_key:
      url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
      state: present

  - name: Add Spotify apt repo
    become: yes
    become_user: root
    apt_repository:
      repo: deb http://repository.spotify.com stable non-free
      state: present

  - name: Update apt cache
    become: yes
    become_user: root
    apt:
      update_cache: yes

  - name: Install spotify-client
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: spotify-client
