# From https://code.visualstudio.com/docs/setup/linux
# TODO https://rust-analyzer.github.io/

- hosts: all
  gather_facts: false
  tasks:

  - name: Install apt-transport-https
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: apt-transport-https

  - name: Install official repository signing key
    become: yes
    become_user: root
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present

  - name: Add repository to list of repositories
    become: yes
    become_user: root
    apt_repository:
      repo: deb https://packages.microsoft.com/repos/code stable main
      state: present

  - name: Update apt cache, if older than a day
    become: yes
    become_user: root
    apt:
      update_cache: yes
      cache_valid_time: 86400

  - name: Install Visual Studio Code
    become: yes
    become_user: root
    apt:
      state: latest
      pkg: code
