- import_playbook: create-user-bin.yaml

- hosts: all
  tasks:

  - name: Install rootless docker
    shell: "curl -fsSL https://get.docker.com/rootless | sh"

  - name: Start Docker registry service
    systemd:
      scope: user
      name: docker
      enabled: yes
      state: started
      daemon_reload: yes

  - name: export DOCKER_HOST in .bashrc
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.bashrc"
      line: export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
